#!/usr/bin/bash
dirname=$(date +"%d-%m-%Y")
subdirname=$(date +"%T")
mkdir -p ~/minecraft_backups/"$dirname"/"$subdirname"
cp -r ~/.minecraft/saves/* ~/minecraft_backups/"$dirname"/"$subdirname"/
echo "backup created on ${dirname} at ${subdirname}"
