#!/usr/bin/bash
mkdir -p ~/minecraft_backups
dirname=$(date +"%d-%m-%Y")
subdirname=$(date +"%k:%M:%S")
mkdir -p ~/minecraft_backups/$dirname/$subdirname
cp -r ~/.minecraft/saves/* ~/minecraft_backups/$dirname/$subdirname/
echo "backup created at ${dirname}"
